# ---
# - hosts: localhost
#   connection: local
#   become: true
#   tasks:
#     - name: Stop NGINX
#       service:
#         name: nginx
#         state: stopped

#     - name: Remove NGINX
#       apt:
#         name: nginx
#         state: absent
#         purge: yes

#     - name: Stop MySQL
#       service:
#         name: mysql
#         state: stopped

#     - name: Remove MySQL server
#       apt:
#         name: mysql-server
#         state: absent
#         purge: yes

#     - name: Remove MySQL configuration files
#       file:
#         path: /etc/mysql
#         state: absent
#         recurse: yes

#     # Uninstall Node.js and npm
#     - name: Remove Node.js
#       apt:
#         name: nodejs
#         state: absent
#         purge: yes

#     - name: Remove npm
#       apt:
#         name: npm
#         state: absent
#         purge: yes

#     # Optional: Remove NodeSource repository
#     - name: Remove NodeSource repository
#       apt_repository:
#         repo: deb https://deb.nodesource.com/node_20.x jammy main
#         state: absent


# ---
# - hosts: localhost
#   connection: local
#   become: true
#   tasks:
#     - name: Stop NGINX
#       service:
#         name: nginx
#         state: stopped

#     - name: Remove NGINX
#       apt:
#         name: nginx
#         state: absent
#         purge: yes

#     - name: Stop MySQL
#       service:
#         name: mysql
#         state: stopped

#     - name: Remove MySQL server
#       apt:
#         name: mysql-server
#         state: absent
#         purge: yes

#     - name: Debug directory before removal
#       command: ls -ld /etc/mysql
#       register: mysql_dir
#       ignore_errors: yes

#     - debug:
#         var: mysql_dir

#     - name: Remove MySQL configuration files
#       file:
#         path: /etc/mysql
#         state: absent
#         recurse: yes


---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Stop NGINX
      service:
        name: nginx
        state: stopped

    - name: Remove NGINX
      apt:
        name: nginx
        state: absent
        purge: yes

    - name: Stop MySQL
      service:
        name: mysql
        state: stopped

    - name: Remove MySQL server
      apt:
        name: mysql-server
        state: absent
        purge: yes

    - name: Ensure /etc/mysql directory exists
      file:
        path: /etc/mysql
        state: directory
      ignore_errors: yes

    - name: Attempt to remove MySQL configuration files
      file:
        path: /etc/mysql
        state: absent
        recurse: yes
      register: remove_mysql_config_files
      ignore_errors: yes

    - name: Debug the result of the directory removal
      debug:
        var: remove_mysql_config_files

    - name: Fallback - Remove MySQL configuration files with shell
      shell: rm -rf /etc/mysql
      when: remove_mysql_config_files.failed
      ignore_errors: yes

    - name: Remove Node.js
      apt:
        name: nodejs
        state: absent
        purge: yes

    - name: Remove npm
      apt:
        name: npm
        state: absent
        purge: yes

    - name: Remove NodeSource repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_20.x jammy main
        state: absent