---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL server
  apt:
    name: mysql-server-8.0
    state: present
  ignore_errors: yes  # Ignore errors temporarily for troubleshooting

- name: Ensure MySQL service is running and enabled
  service:
    name: mysql
    state: started
    enabled: yes
  ignore_errors: yes  # Ignore errors temporarily for troubleshooting

- name: Deploy MySQL configuration file
  copy:
    src: ../files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644
    owner: mysql
    group: mysql
  notify:
    - Restart MySQL

# Execute the bash script to create MySQL user 'manager'
- name: Create MySQL user 'manager' using bash script
  script: ../files/create_mysql_user.sh
  args:
    executable: /bin/bash
  become: yes # Adjust the path based on where bash is installed
   