---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL server
  apt:
    name: mysql-server-8.0
    state: present
  ignore_errors: yes  # Ignore errors temporarily for troubleshooting

- name: Ensure MySQL service is running and enabled
  service:
    name: mysql
    state: started
    enabled: yes
  ignore_errors: yes  # Ignore errors temporarily for troubleshooting

- name: Deploy MySQL configuration file
  copy:
    src: ../files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644
    owner: mysql
    group: mysql
  notify:
    - Restart MySQL

- name: Set MySQL root password
  mysql_user:
    name: root
    password: 12345
    host_all: yes
    state: present
  ignore_errors: yes

- name: Create MySQL user 'manager' with all privileges
  mysql_user:
    name: manager
    password: 12345
    priv: '*.*:ALL'
    host: '%'
    state: present
  notify:
    - Restart MySQL

# handlers:
#   - name: Restart MySQL
#     service:
#       name: mysql
#       state: restarted