---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true

- name: Deploy MySQL configuration
  copy:
    src: ../files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644
    owner: mysql
    group: mysql
  notify:
    - Restart MySQL

- name: Set MySQL root password
  mysql_user:
    name: root
    password: 12345
    host_all: yes
    state: present

- name: Create MySQL user 'manager' with all privileges
  mysql_user:
    name: manager
    password: 12345
    priv: '*.*:ALL'
    host: '%'
    state: present
  notify:
    - Restart MySQL